# Generated by Django 2.2.5 on 2019-09-19 13:06

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Сообщение')),
                ('send_date', models.DateTimeField(verbose_name='Дата отправки')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('to_sex', multiselectfield.db.fields.MultiSelectField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=3, verbose_name='Пол')),
                ('to_countries', multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name='Страны')),
                ('for_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tried', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.Distribution', verbose_name='Рассылка')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Recipient', verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
    ]
