# Generated by Django 2.2.3 on 2019-07-30 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('send_date', models.DateTimeField()),
                ('rec_ids', models.CharField(max_length=30000)),
            ],
        ),
        migrations.CreateModel(
            name='DistributionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.Distribution')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Recipient')),
            ],
        ),
    ]
