# Generated by Django 2.2.5 on 2019-09-20 11:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributionitem',
            old_name='tried',
            new_name='is_tried_send',
        ),
        migrations.AlterField(
            model_name='distribution',
            name='to_countries',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Россия', 'Россия'), ('Киргизия', 'Киргизия'), ('Казахстан', 'Казахстан'), ('Республика Беларусь', 'Республика Беларусь')], max_length=45, verbose_name='Страны'),
        ),
    ]
