# Generated by Django 2.2.3 on 2019-07-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribution',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
