# Generated by Django 2.2.3 on 2019-08-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_add_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='countries',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
