# Generated by Django 2.2.3 on 2019-07-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_distribution_is_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionitem',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
