# Generated by Django 2.2.3 on 2019-08-05 09:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_distributionitem_is_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
