# Generated by Django 2.2.3 on 2019-08-18 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_auto_20190819_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='countries',
            new_name='country',
        ),
    ]
