# Generated by Django 2.2.5 on 2019-09-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_add_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributionitem',
            name='is_tried_send',
        ),
        migrations.AddField(
            model_name='distributionitem',
            name='try_count',
            field=models.IntegerField(default=0),
        ),
    ]
