# Generated by Django 2.2.3 on 2019-08-11 12:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_auto_20190805_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='distributionitem',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterField(
            model_name='distribution',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='rec_ids',
            field=models.TextField(verbose_name='Не трогайте!'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='send_date',
            field=models.DateTimeField(verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='distribution',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.Distribution', verbose_name='Рассылка'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='distributionitem',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Recipient', verbose_name='Получатель'),
        ),
    ]
