# Generated by Django 2.2.5 on 2019-09-23 11:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0004_auto_20190921_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='to_countries',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, verbose_name='Страны'),
        ),
    ]
