# Generated by Django 2.2.3 on 2019-08-15 02:20

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_auto_20190811_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Сообщение'),
        ),
    ]
