# Generated by Django 2.2.5 on 2019-09-25 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_auto_20190923_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='to_countries',
            field=models.CharField(choices=[('ALL', 'Все страны'), ('Россия', 'Россия'), ('Киргизия', 'Киргизия'), ('Казахстан', 'Казахстан'), ('Республика Беларусь', 'Республика Беларусь')], max_length=5000, verbose_name='Страны'),
        ),
    ]
