# Generated by Django 2.2.5 on 2019-09-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_auto_20190925_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='to_countries',
            field=models.CharField(max_length=5000, verbose_name='Страны'),
        ),
    ]
