# Generated by Django 2.2.5 on 2019-09-19 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('excel_file', models.FileField(upload_to='event/', verbose_name='Excel с участниками')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('birth_date', models.CharField(max_length=200, verbose_name='Дата рождения')),
                ('sex', models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=50, verbose_name='Пол')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('phone', models.CharField(max_length=200, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('distance', models.CharField(max_length=100, verbose_name='Дистанция')),
                ('register_date', models.CharField(max_length=100, verbose_name='Дата регистрации')),
                ('pay_status', models.CharField(max_length=100, verbose_name='Статус оплаты')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
