# Generated by Django 2.2.5 on 2019-09-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='birth_date',
            field=models.CharField(max_length=200, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='distance',
            field=models.CharField(max_length=100, null=True, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='pay_status',
            field=models.CharField(max_length=100, null=True, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='register_date',
            field=models.CharField(max_length=100, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='surname',
            field=models.CharField(max_length=200, null=True, verbose_name='Фамилия'),
        ),
    ]
