# Generated by Django 2.2.3 on 2019-08-11 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='recipient',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='event',
            name='excel_file',
            field=models.FileField(upload_to='event/', verbose_name='.XLS файл с участниками'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='birth_date',
            field=models.CharField(max_length=200, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='country',
            field=models.CharField(max_length=100, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='distance',
            field=models.CharField(max_length=100, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.Event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='pay_status',
            field=models.CharField(max_length=100, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='register_date',
            field=models.CharField(max_length=100, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='sex',
            field=models.CharField(choices=[('М', 'М'), ('Ж', 'Ж')], max_length=50, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
    ]
