# Generated by Django 2.2.5 on 2019-09-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190921_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='birth_date_col',
            field=models.CharField(default='a', max_length=3, verbose_name='День рождения'),
        ),
        migrations.AddField(
            model_name='event',
            name='country_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='event',
            name='distance_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Дистанция'),
        ),
        migrations.AddField(
            model_name='event',
            name='email_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='event',
            name='name_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='event',
            name='pay_status_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Статуч оплаты'),
        ),
        migrations.AddField(
            model_name='event',
            name='phone_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='event',
            name='register_date_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='event',
            name='sex_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='event',
            name='surname_col',
            field=models.CharField(default='a', max_length=3, verbose_name='Фамилия'),
        ),
    ]
