# Generated by Django 2.2.5 on 2019-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190923_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='birth_date_col',
            field=models.CharField(default='C', max_length=2, verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='country_col',
            field=models.CharField(default='E', max_length=2, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='event',
            name='distance_col',
            field=models.CharField(default='H', max_length=2, verbose_name='Дистанция'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email_col',
            field=models.CharField(default='G', max_length=2, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name_col',
            field=models.CharField(default='A', max_length=2, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='event',
            name='pay_status_col',
            field=models.CharField(default='J', max_length=2, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_col',
            field=models.CharField(default='F', max_length=2, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='event',
            name='register_date_col',
            field=models.CharField(default='I', max_length=2, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sex_col',
            field=models.CharField(default='D', max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='event',
            name='surname_col',
            field=models.CharField(default='B', max_length=2, verbose_name='Фамилия'),
        ),
    ]
